### ISSUE TITLE
guide for production setup 

### ISSUE THREAD

**Issue by piyushmani-raj** [kkworden/django-react-starterpack#2]
Hi , I flowed your blog so setup react and it works.
can you please guide me to setup for prod env.
I also want to store my assets to S3

**Comment by kkworden** [comment]
Hey, for production you will probably want to start by disabling Django's `Debug` mode: https://github.com/kkworden/django-react-starterpack/blob/master/project/settings.py

Then, you will need to get AWS credentials into your environment somehow... if you run the server on an AWS EC2 instance, your environment will be able to make calls directly to S3 using `botocore`. I would check out: https://github.com/boto/botocore

Good luck!
